// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBreaksByOrg = `-- name: DeleteBreaksByOrg :exec
DELETE FROM availability_breaks
WHERE organization_id = $1
`

func (q *Queries) DeleteBreaksByOrg(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBreaksByOrg, organizationID)
	return err
}

const deleteTimeOffByOrg = `-- name: DeleteTimeOffByOrg :exec
DELETE FROM availability_time_off
WHERE organization_id = $1
`

func (q *Queries) DeleteTimeOffByOrg(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimeOffByOrg, organizationID)
	return err
}

const deleteWorkingHoursByOrg = `-- name: DeleteWorkingHoursByOrg :exec
DELETE FROM availability_working_hours
WHERE organization_id = $1
`

func (q *Queries) DeleteWorkingHoursByOrg(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkingHoursByOrg, organizationID)
	return err
}

const getAvailabilityByOrg = `-- name: GetAvailabilityByOrg :one
SELECT
    s.organization_id,
    s.timezone,
    s.max_interviews_per_day,
    s.booking_horizon_days,
    s.updated_at,
    COALESCE((
        SELECT json_agg(
            json_build_object(
                'id', wh.id,
                'day_of_week', wh.day_of_week,
                'start_time', wh.start_time,
                'end_time', wh.end_time,
                'created_at', wh.created_at
            )
            ORDER BY wh.day_of_week, wh.start_time
        )
        FROM availability_working_hours wh
        WHERE wh.organization_id = s.organization_id
    ), '[]'::json) AS working_hours,
    COALESCE((
        SELECT json_agg(
            json_build_object(
                'id', b.id,
                'day_of_week', b.day_of_week,
                'start_time', b.start_time,
                'end_time', b.end_time
            )
            ORDER BY b.day_of_week, b.start_time
        )
        FROM availability_breaks b
        WHERE b.organization_id = s.organization_id
    ), '[]'::json) AS breaks,
    COALESCE((
        SELECT json_agg(
            json_build_object(
                'id', t.id,
                'start_at', t.start_at,
                'end_at', t.end_at
            )
            ORDER BY t.start_at, t.end_at
        )
        FROM availability_time_off t
        WHERE t.organization_id = s.organization_id
    ), '[]'::json) AS time_off
FROM availability_settings s
WHERE s.organization_id = $1
`

type GetAvailabilityByOrgRow struct {
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	Timezone            string             `json:"timezone"`
	MaxInterviewsPerDay int32              `json:"max_interviews_per_day"`
	BookingHorizonDays  int32              `json:"booking_horizon_days"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	WorkingHours        interface{}        `json:"working_hours"`
	Breaks              interface{}        `json:"breaks"`
	TimeOff             interface{}        `json:"time_off"`
}

func (q *Queries) GetAvailabilityByOrg(ctx context.Context, organizationID pgtype.UUID) (GetAvailabilityByOrgRow, error) {
	row := q.db.QueryRow(ctx, getAvailabilityByOrg, organizationID)
	var i GetAvailabilityByOrgRow
	err := row.Scan(
		&i.OrganizationID,
		&i.Timezone,
		&i.MaxInterviewsPerDay,
		&i.BookingHorizonDays,
		&i.UpdatedAt,
		&i.WorkingHours,
		&i.Breaks,
		&i.TimeOff,
	)
	return i, err
}

const getAvailabilitySettingsByOrg = `-- name: GetAvailabilitySettingsByOrg :one
SELECT organization_id, timezone, max_interviews_per_day, updated_at, booking_horizon_days
FROM availability_settings
WHERE organization_id = $1
`

func (q *Queries) GetAvailabilitySettingsByOrg(ctx context.Context, organizationID pgtype.UUID) (AvailabilitySetting, error) {
	row := q.db.QueryRow(ctx, getAvailabilitySettingsByOrg, organizationID)
	var i AvailabilitySetting
	err := row.Scan(
		&i.OrganizationID,
		&i.Timezone,
		&i.MaxInterviewsPerDay,
		&i.UpdatedAt,
		&i.BookingHorizonDays,
	)
	return i, err
}

const insertBreak = `-- name: InsertBreak :exec
INSERT INTO availability_breaks (
    organization_id,
    day_of_week,
    start_time,
    end_time
)
VALUES ($1, $2, $3, $4)
`

type InsertBreakParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	DayOfWeek      int16       `json:"day_of_week"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
}

func (q *Queries) InsertBreak(ctx context.Context, arg InsertBreakParams) error {
	_, err := q.db.Exec(ctx, insertBreak,
		arg.OrganizationID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}

const insertTimeOff = `-- name: InsertTimeOff :one
INSERT INTO availability_time_off (
    organization_id,
    start_at,
    end_at
)
VALUES ($1, $2, $3)
RETURNING id, organization_id, end_at, start_at
`

type InsertTimeOffParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	EndAt          pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) InsertTimeOff(ctx context.Context, arg InsertTimeOffParams) (AvailabilityTimeOff, error) {
	row := q.db.QueryRow(ctx, insertTimeOff, arg.OrganizationID, arg.StartAt, arg.EndAt)
	var i AvailabilityTimeOff
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EndAt,
		&i.StartAt,
	)
	return i, err
}

const insertWorkingHour = `-- name: InsertWorkingHour :exec
INSERT INTO availability_working_hours (
    organization_id,
    day_of_week,
    start_time,
    end_time
)
VALUES ($1, $2, $3, $4)
`

type InsertWorkingHourParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	DayOfWeek      int16       `json:"day_of_week"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
}

func (q *Queries) InsertWorkingHour(ctx context.Context, arg InsertWorkingHourParams) error {
	_, err := q.db.Exec(ctx, insertWorkingHour,
		arg.OrganizationID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}

const listBreaksByOrg = `-- name: ListBreaksByOrg :many
SELECT id, organization_id, day_of_week, start_time, end_time
FROM availability_breaks
WHERE organization_id = $1
ORDER BY day_of_week, start_time
`

func (q *Queries) ListBreaksByOrg(ctx context.Context, organizationID pgtype.UUID) ([]AvailabilityBreak, error) {
	rows, err := q.db.Query(ctx, listBreaksByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityBreak{}
	for rows.Next() {
		var i AvailabilityBreak
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeOffByOrg = `-- name: ListTimeOffByOrg :many
SELECT id, organization_id, end_at, start_at
FROM availability_time_off
WHERE organization_id = $1
ORDER BY start_at, end_at
`

func (q *Queries) ListTimeOffByOrg(ctx context.Context, organizationID pgtype.UUID) ([]AvailabilityTimeOff, error) {
	rows, err := q.db.Query(ctx, listTimeOffByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityTimeOff{}
	for rows.Next() {
		var i AvailabilityTimeOff
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EndAt,
			&i.StartAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkingHoursByOrg = `-- name: ListWorkingHoursByOrg :many
SELECT id, organization_id, day_of_week, start_time, end_time, created_at
FROM availability_working_hours
WHERE organization_id = $1
ORDER BY day_of_week, start_time
`

func (q *Queries) ListWorkingHoursByOrg(ctx context.Context, organizationID pgtype.UUID) ([]AvailabilityWorkingHour, error) {
	rows, err := q.db.Query(ctx, listWorkingHoursByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityWorkingHour{}
	for rows.Next() {
		var i AvailabilityWorkingHour
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAvailabilitySettings = `-- name: UpsertAvailabilitySettings :exec
INSERT INTO availability_settings (
    organization_id,
    timezone,
    max_interviews_per_day,
    booking_horizon_days
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (organization_id) DO UPDATE
SET
    timezone = EXCLUDED.timezone,
    max_interviews_per_day = EXCLUDED.max_interviews_per_day,
    booking_horizon_days = EXCLUDED.booking_horizon_days,
    updated_at = NOW()
`

type UpsertAvailabilitySettingsParams struct {
	OrganizationID      pgtype.UUID `json:"organization_id"`
	Timezone            string      `json:"timezone"`
	MaxInterviewsPerDay int32       `json:"max_interviews_per_day"`
	BookingHorizonDays  int32       `json:"booking_horizon_days"`
}

func (q *Queries) UpsertAvailabilitySettings(ctx context.Context, arg UpsertAvailabilitySettingsParams) error {
	_, err := q.db.Exec(ctx, upsertAvailabilitySettings,
		arg.OrganizationID,
		arg.Timezone,
		arg.MaxInterviewsPerDay,
		arg.BookingHorizonDays,
	)
	return err
}
