// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE booking
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND status = 'scheduled'
RETURNING id, organization_id, interview_type_id, slot_id, candidate_name, candidate_phone, candidate_email, status, meet_link, calendar_event_id, reschedule_token, cancel_token, created_at, updated_at
`

type CancelBookingParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, cancelBooking, arg.ID, arg.OrganizationID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countBookingsBySlot = `-- name: CountBookingsBySlot :one
SELECT COUNT(*)::int
FROM booking
WHERE slot_id = $1
`

func (q *Queries) CountBookingsBySlot(ctx context.Context, slotID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBookingsBySlot, slotID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, organization_id, interview_type_id, slot_id, candidate_name, candidate_phone, candidate_email, status, meet_link, calendar_event_id, reschedule_token, cancel_token, created_at, updated_at
FROM booking
WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduledBookingByCancelToken = `-- name: GetScheduledBookingByCancelToken :one
SELECT
    b.id, b.organization_id, b.interview_type_id, b.slot_id, b.candidate_name, b.candidate_phone, b.candidate_email, b.status, b.meet_link, b.calendar_event_id, b.reschedule_token, b.cancel_token, b.created_at, b.updated_at,
    s.start_at AS slot_start_at,
    s.end_at AS slot_end_at
FROM booking b
JOIN slots s ON s.id = b.slot_id
WHERE b.cancel_token = $1
  AND b.status = 'scheduled'
`

type GetScheduledBookingByCancelTokenRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	SlotID          pgtype.UUID        `json:"slot_id"`
	CandidateName   string             `json:"candidate_name"`
	CandidatePhone  string             `json:"candidate_phone"`
	CandidateEmail  string             `json:"candidate_email"`
	Status          BookingStatus      `json:"status"`
	MeetLink        pgtype.Text        `json:"meet_link"`
	CalendarEventID pgtype.Text        `json:"calendar_event_id"`
	RescheduleToken string             `json:"reschedule_token"`
	CancelToken     string             `json:"cancel_token"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SlotStartAt     pgtype.Timestamptz `json:"slot_start_at"`
	SlotEndAt       pgtype.Timestamptz `json:"slot_end_at"`
}

func (q *Queries) GetScheduledBookingByCancelToken(ctx context.Context, cancelToken string) (GetScheduledBookingByCancelTokenRow, error) {
	row := q.db.QueryRow(ctx, getScheduledBookingByCancelToken, cancelToken)
	var i GetScheduledBookingByCancelTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlotStartAt,
		&i.SlotEndAt,
	)
	return i, err
}

const getScheduledBookingByCancelTokenForUpdate = `-- name: GetScheduledBookingByCancelTokenForUpdate :one
SELECT
    b.id, b.organization_id, b.interview_type_id, b.slot_id, b.candidate_name, b.candidate_phone, b.candidate_email, b.status, b.meet_link, b.calendar_event_id, b.reschedule_token, b.cancel_token, b.created_at, b.updated_at,
    s.start_at AS slot_start_at,
    s.end_at AS slot_end_at
FROM booking b
JOIN slots s ON s.id = b.slot_id
WHERE b.cancel_token = $1
  AND b.status = 'scheduled'
FOR UPDATE OF b
`

type GetScheduledBookingByCancelTokenForUpdateRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	SlotID          pgtype.UUID        `json:"slot_id"`
	CandidateName   string             `json:"candidate_name"`
	CandidatePhone  string             `json:"candidate_phone"`
	CandidateEmail  string             `json:"candidate_email"`
	Status          BookingStatus      `json:"status"`
	MeetLink        pgtype.Text        `json:"meet_link"`
	CalendarEventID pgtype.Text        `json:"calendar_event_id"`
	RescheduleToken string             `json:"reschedule_token"`
	CancelToken     string             `json:"cancel_token"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SlotStartAt     pgtype.Timestamptz `json:"slot_start_at"`
	SlotEndAt       pgtype.Timestamptz `json:"slot_end_at"`
}

func (q *Queries) GetScheduledBookingByCancelTokenForUpdate(ctx context.Context, cancelToken string) (GetScheduledBookingByCancelTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getScheduledBookingByCancelTokenForUpdate, cancelToken)
	var i GetScheduledBookingByCancelTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlotStartAt,
		&i.SlotEndAt,
	)
	return i, err
}

const getScheduledBookingByRescheduleToken = `-- name: GetScheduledBookingByRescheduleToken :one
SELECT
    b.id, b.organization_id, b.interview_type_id, b.slot_id, b.candidate_name, b.candidate_phone, b.candidate_email, b.status, b.meet_link, b.calendar_event_id, b.reschedule_token, b.cancel_token, b.created_at, b.updated_at,
    s.start_at AS slot_start_at,
    s.end_at AS slot_end_at
FROM booking b
JOIN slots s ON s.id = b.slot_id
WHERE b.reschedule_token = $1
  AND b.status = 'scheduled'
`

type GetScheduledBookingByRescheduleTokenRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	SlotID          pgtype.UUID        `json:"slot_id"`
	CandidateName   string             `json:"candidate_name"`
	CandidatePhone  string             `json:"candidate_phone"`
	CandidateEmail  string             `json:"candidate_email"`
	Status          BookingStatus      `json:"status"`
	MeetLink        pgtype.Text        `json:"meet_link"`
	CalendarEventID pgtype.Text        `json:"calendar_event_id"`
	RescheduleToken string             `json:"reschedule_token"`
	CancelToken     string             `json:"cancel_token"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SlotStartAt     pgtype.Timestamptz `json:"slot_start_at"`
	SlotEndAt       pgtype.Timestamptz `json:"slot_end_at"`
}

func (q *Queries) GetScheduledBookingByRescheduleToken(ctx context.Context, rescheduleToken string) (GetScheduledBookingByRescheduleTokenRow, error) {
	row := q.db.QueryRow(ctx, getScheduledBookingByRescheduleToken, rescheduleToken)
	var i GetScheduledBookingByRescheduleTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlotStartAt,
		&i.SlotEndAt,
	)
	return i, err
}

const getScheduledBookingByRescheduleTokenForUpdate = `-- name: GetScheduledBookingByRescheduleTokenForUpdate :one
SELECT
    b.id, b.organization_id, b.interview_type_id, b.slot_id, b.candidate_name, b.candidate_phone, b.candidate_email, b.status, b.meet_link, b.calendar_event_id, b.reschedule_token, b.cancel_token, b.created_at, b.updated_at,
    s.start_at AS slot_start_at,
    s.end_at AS slot_end_at
FROM booking b
JOIN slots s ON s.id = b.slot_id
WHERE b.reschedule_token = $1
  AND b.status = 'scheduled'
FOR UPDATE OF b
`

type GetScheduledBookingByRescheduleTokenForUpdateRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	SlotID          pgtype.UUID        `json:"slot_id"`
	CandidateName   string             `json:"candidate_name"`
	CandidatePhone  string             `json:"candidate_phone"`
	CandidateEmail  string             `json:"candidate_email"`
	Status          BookingStatus      `json:"status"`
	MeetLink        pgtype.Text        `json:"meet_link"`
	CalendarEventID pgtype.Text        `json:"calendar_event_id"`
	RescheduleToken string             `json:"reschedule_token"`
	CancelToken     string             `json:"cancel_token"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SlotStartAt     pgtype.Timestamptz `json:"slot_start_at"`
	SlotEndAt       pgtype.Timestamptz `json:"slot_end_at"`
}

func (q *Queries) GetScheduledBookingByRescheduleTokenForUpdate(ctx context.Context, rescheduleToken string) (GetScheduledBookingByRescheduleTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getScheduledBookingByRescheduleTokenForUpdate, rescheduleToken)
	var i GetScheduledBookingByRescheduleTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlotStartAt,
		&i.SlotEndAt,
	)
	return i, err
}

const getScheduledBookingForUpdate = `-- name: GetScheduledBookingForUpdate :one
SELECT b.id, b.organization_id, b.interview_type_id, b.slot_id, b.candidate_name, b.candidate_phone, b.candidate_email, b.status, b.meet_link, b.calendar_event_id, b.reschedule_token, b.cancel_token, b.created_at, b.updated_at
FROM booking b
WHERE b.id = $1
  AND b.organization_id = $2
  AND b.status = 'scheduled'
FOR UPDATE
`

type GetScheduledBookingForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetScheduledBookingForUpdate(ctx context.Context, arg GetScheduledBookingForUpdateParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getScheduledBookingForUpdate, arg.ID, arg.OrganizationID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlotForUpdate = `-- name: GetSlotForUpdate :one
SELECT id, organization_id, interview_type_id, start_at, end_at, booked, created_at
FROM slots
WHERE id = $1
  AND organization_id = $2
  AND interview_type_id = $3
  AND booked = FALSE
FOR UPDATE
`

type GetSlotForUpdateParams struct {
	ID              pgtype.UUID `json:"id"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	InterviewTypeID pgtype.UUID `json:"interview_type_id"`
}

func (q *Queries) GetSlotForUpdate(ctx context.Context, arg GetSlotForUpdateParams) (Slot, error) {
	row := q.db.QueryRow(ctx, getSlotForUpdate, arg.ID, arg.OrganizationID, arg.InterviewTypeID)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.StartAt,
		&i.EndAt,
		&i.Booked,
		&i.CreatedAt,
	)
	return i, err
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO booking (
    organization_id,
    interview_type_id,
    slot_id,
    candidate_name,
    candidate_phone,
    candidate_email,
    reschedule_token,
    cancel_token
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, interview_type_id, slot_id, candidate_name, candidate_phone, candidate_email, status, meet_link, calendar_event_id, reschedule_token, cancel_token, created_at, updated_at
`

type InsertBookingParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	InterviewTypeID pgtype.UUID `json:"interview_type_id"`
	SlotID          pgtype.UUID `json:"slot_id"`
	CandidateName   string      `json:"candidate_name"`
	CandidatePhone  string      `json:"candidate_phone"`
	CandidateEmail  string      `json:"candidate_email"`
	RescheduleToken string      `json:"reschedule_token"`
	CancelToken     string      `json:"cancel_token"`
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.OrganizationID,
		arg.InterviewTypeID,
		arg.SlotID,
		arg.CandidateName,
		arg.CandidatePhone,
		arg.CandidateEmail,
		arg.RescheduleToken,
		arg.CancelToken,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationOutboxByOrg = `-- name: ListNotificationOutboxByOrg :many
SELECT id, organization_id, event_type, payload, status, retry_count, created_at, processed_at
FROM notification_outbox
WHERE organization_id = $1
ORDER BY created_at
`

func (q *Queries) ListNotificationOutboxByOrg(ctx context.Context, organizationID pgtype.UUID) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, listNotificationOutboxByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationOutbox{}
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledBookingsByOrg = `-- name: ListScheduledBookingsByOrg :many
SELECT
    b.id, b.organization_id, b.interview_type_id, b.slot_id, b.candidate_name, b.candidate_phone, b.candidate_email, b.status, b.meet_link, b.calendar_event_id, b.reschedule_token, b.cancel_token, b.created_at, b.updated_at,
    s.start_at,
    s.end_at,
    it.title AS interview_type_title
FROM booking b
JOIN slots s ON s.id = b.slot_id
JOIN interview_type it ON it.id = b.interview_type_id
WHERE b.organization_id = $1
  AND b.status = 'scheduled'
  AND s.start_at >= $2
ORDER BY s.start_at
`

type ListScheduledBookingsByOrgParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
}

type ListScheduledBookingsByOrgRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	InterviewTypeID    pgtype.UUID        `json:"interview_type_id"`
	SlotID             pgtype.UUID        `json:"slot_id"`
	CandidateName      string             `json:"candidate_name"`
	CandidatePhone     string             `json:"candidate_phone"`
	CandidateEmail     string             `json:"candidate_email"`
	Status             BookingStatus      `json:"status"`
	MeetLink           pgtype.Text        `json:"meet_link"`
	CalendarEventID    pgtype.Text        `json:"calendar_event_id"`
	RescheduleToken    string             `json:"reschedule_token"`
	CancelToken        string             `json:"cancel_token"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	InterviewTypeTitle string             `json:"interview_type_title"`
}

func (q *Queries) ListScheduledBookingsByOrg(ctx context.Context, arg ListScheduledBookingsByOrgParams) ([]ListScheduledBookingsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listScheduledBookingsByOrg, arg.OrganizationID, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledBookingsByOrgRow{}
	for rows.Next() {
		var i ListScheduledBookingsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InterviewTypeID,
			&i.SlotID,
			&i.CandidateName,
			&i.CandidatePhone,
			&i.CandidateEmail,
			&i.Status,
			&i.MeetLink,
			&i.CalendarEventID,
			&i.RescheduleToken,
			&i.CancelToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartAt,
			&i.EndAt,
			&i.InterviewTypeTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSlotBooked = `-- name: MarkSlotBooked :execrows
UPDATE slots
SET booked = TRUE
WHERE id = $1
  AND booked = FALSE
`

func (q *Queries) MarkSlotBooked(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSlotBooked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBookingMeetInfo = `-- name: UpdateBookingMeetInfo :one
UPDATE booking
SET
    meet_link = $2,
    calendar_event_id = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, interview_type_id, slot_id, candidate_name, candidate_phone, candidate_email, status, meet_link, calendar_event_id, reschedule_token, cancel_token, created_at, updated_at
`

type UpdateBookingMeetInfoParams struct {
	ID              pgtype.UUID `json:"id"`
	MeetLink        pgtype.Text `json:"meet_link"`
	CalendarEventID pgtype.Text `json:"calendar_event_id"`
}

func (q *Queries) UpdateBookingMeetInfo(ctx context.Context, arg UpdateBookingMeetInfoParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingMeetInfo, arg.ID, arg.MeetLink, arg.CalendarEventID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingSlot = `-- name: UpdateBookingSlot :one
UPDATE booking
SET slot_id = $2, updated_at = NOW()
WHERE id = $1
  AND status = 'scheduled'
RETURNING id, organization_id, interview_type_id, slot_id, candidate_name, candidate_phone, candidate_email, status, meet_link, calendar_event_id, reschedule_token, cancel_token, created_at, updated_at
`

type UpdateBookingSlotParams struct {
	ID     pgtype.UUID `json:"id"`
	SlotID pgtype.UUID `json:"slot_id"`
}

func (q *Queries) UpdateBookingSlot(ctx context.Context, arg UpdateBookingSlotParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingSlot, arg.ID, arg.SlotID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.SlotID,
		&i.CandidateName,
		&i.CandidatePhone,
		&i.CandidateEmail,
		&i.Status,
		&i.MeetLink,
		&i.CalendarEventID,
		&i.RescheduleToken,
		&i.CancelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
