// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkInsertSlots implements pgx.CopyFromSource.
type iteratorForBulkInsertSlots struct {
	rows                 []BulkInsertSlotsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertSlots) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertSlots) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrganizationID,
		r.rows[0].InterviewTypeID,
		r.rows[0].StartAt,
		r.rows[0].EndAt,
	}, nil
}

func (r iteratorForBulkInsertSlots) Err() error {
	return nil
}

func (q *Queries) BulkInsertSlots(ctx context.Context, arg []BulkInsertSlotsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"slots"}, []string{"organization_id", "interview_type_id", "start_at", "end_at"}, &iteratorForBulkInsertSlots{rows: arg})
}
