// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interview_types.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInterviewTypesByOrg = `-- name: CountInterviewTypesByOrg :one
SELECT COUNT(*)::int
FROM interview_type
WHERE organization_id = $1
`

func (q *Queries) CountInterviewTypesByOrg(ctx context.Context, organizationID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countInterviewTypesByOrg, organizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInterviewType = `-- name: CreateInterviewType :one
INSERT INTO interview_type (
    organization_id,
    title,
    slug,
    duration_minutes,
    buffer_minutes,
    meeting_provider,
    meeting_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, title, slug, duration_minutes, buffer_minutes, meeting_provider, meeting_url, created_at, updated_at
`

type CreateInterviewTypeParams struct {
	OrganizationID  pgtype.UUID     `json:"organization_id"`
	Title           string          `json:"title"`
	Slug            string          `json:"slug"`
	DurationMinutes int32           `json:"duration_minutes"`
	BufferMinutes   int32           `json:"buffer_minutes"`
	MeetingProvider MeetingProvider `json:"meeting_provider"`
	MeetingUrl      pgtype.Text     `json:"meeting_url"`
}

func (q *Queries) CreateInterviewType(ctx context.Context, arg CreateInterviewTypeParams) (InterviewType, error) {
	row := q.db.QueryRow(ctx, createInterviewType,
		arg.OrganizationID,
		arg.Title,
		arg.Slug,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.MeetingProvider,
		arg.MeetingUrl,
	)
	var i InterviewType
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Slug,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.MeetingProvider,
		&i.MeetingUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInterviewTypeByID = `-- name: GetInterviewTypeByID :one
SELECT id, organization_id, title, slug, duration_minutes, buffer_minutes, meeting_provider, meeting_url, created_at, updated_at
FROM interview_type
WHERE id = $1
`

func (q *Queries) GetInterviewTypeByID(ctx context.Context, id pgtype.UUID) (InterviewType, error) {
	row := q.db.QueryRow(ctx, getInterviewTypeByID, id)
	var i InterviewType
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Slug,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.MeetingProvider,
		&i.MeetingUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const interviewTypeExistsBySlug = `-- name: InterviewTypeExistsBySlug :one
SELECT EXISTS (
    SELECT 1
    FROM interview_type
    WHERE organization_id = $1 AND slug = $2
)
`

type InterviewTypeExistsBySlugParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Slug           string      `json:"slug"`
}

func (q *Queries) InterviewTypeExistsBySlug(ctx context.Context, arg InterviewTypeExistsBySlugParams) (bool, error) {
	row := q.db.QueryRow(ctx, interviewTypeExistsBySlug, arg.OrganizationID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInterviewTypesByOrg = `-- name: ListInterviewTypesByOrg :many
SELECT id, organization_id, title, slug, duration_minutes, buffer_minutes, meeting_provider, meeting_url, created_at, updated_at
FROM interview_type
WHERE organization_id = $1
ORDER BY created_at
`

func (q *Queries) ListInterviewTypesByOrg(ctx context.Context, organizationID pgtype.UUID) ([]InterviewType, error) {
	rows, err := q.db.Query(ctx, listInterviewTypesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InterviewType{}
	for rows.Next() {
		var i InterviewType
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.Slug,
			&i.DurationMinutes,
			&i.BufferMinutes,
			&i.MeetingProvider,
			&i.MeetingUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewType = `-- name: UpdateInterviewType :one
UPDATE interview_type
SET
    title = $2,
    slug = $3,
    duration_minutes = $4,
    buffer_minutes = $5,
    meeting_provider = $6,
    meeting_url = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, title, slug, duration_minutes, buffer_minutes, meeting_provider, meeting_url, created_at, updated_at
`

type UpdateInterviewTypeParams struct {
	ID              pgtype.UUID     `json:"id"`
	Title           string          `json:"title"`
	Slug            string          `json:"slug"`
	DurationMinutes int32           `json:"duration_minutes"`
	BufferMinutes   int32           `json:"buffer_minutes"`
	MeetingProvider MeetingProvider `json:"meeting_provider"`
	MeetingUrl      pgtype.Text     `json:"meeting_url"`
}

func (q *Queries) UpdateInterviewType(ctx context.Context, arg UpdateInterviewTypeParams) (InterviewType, error) {
	row := q.db.QueryRow(ctx, updateInterviewType,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.MeetingProvider,
		arg.MeetingUrl,
	)
	var i InterviewType
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Slug,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.MeetingProvider,
		&i.MeetingUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
