// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNotificationOutbox = `-- name: InsertNotificationOutbox :one
INSERT INTO notification_outbox (
    organization_id,
    event_type,
    payload
)
VALUES ($1, $2, $3)
RETURNING id, organization_id, event_type, payload, status, retry_count, created_at, processed_at
`

type InsertNotificationOutboxParams struct {
	OrganizationID pgtype.UUID           `json:"organization_id"`
	EventType      NotificationEventType `json:"event_type"`
	Payload        []byte                `json:"payload"`
}

func (q *Queries) InsertNotificationOutbox(ctx context.Context, arg InsertNotificationOutboxParams) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, insertNotificationOutbox, arg.OrganizationID, arg.EventType, arg.Payload)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}
