// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization (
    name,
    slug,
    logo_url,
    owner_id,
    plan
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, logo_url, owner_id, plan, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
	LogoUrl pgtype.Text `json:"logo_url"`
	OwnerID pgtype.UUID `json:"owner_id"`
	Plan    PlanType    `json:"plan"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.LogoUrl,
		arg.OwnerID,
		arg.Plan,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organization
WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, logo_url, owner_id, plan, created_at, updated_at
FROM organization
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, logo_url, owner_id, plan, created_at, updated_at
FROM organization
WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationsByOwner = `-- name: GetOrganizationsByOwner :one
SELECT id, name, slug, logo_url, owner_id, plan, created_at, updated_at
FROM organization
WHERE owner_id = $1
`

func (q *Queries) GetOrganizationsByOwner(ctx context.Context, ownerID pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationsByOwner, ownerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const organizationExistsBySlug = `-- name: OrganizationExistsBySlug :one
SELECT EXISTS (
    SELECT 1
    FROM organization
    WHERE slug = $1
)
`

func (q *Queries) OrganizationExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, organizationExistsBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organization
SET
    name = $2,
    slug = $3,
    logo_url = $4,
    plan = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, logo_url, owner_id, plan, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
	LogoUrl pgtype.Text `json:"logo_url"`
	Plan    PlanType    `json:"plan"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.LogoUrl,
		arg.Plan,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationLogo = `-- name: UpdateOrganizationLogo :one
UPDATE organization
SET
    logo_url = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, logo_url, owner_id, plan, created_at, updated_at
`

type UpdateOrganizationLogoParams struct {
	ID      pgtype.UUID `json:"id"`
	LogoUrl pgtype.Text `json:"logo_url"`
}

func (q *Queries) UpdateOrganizationLogo(ctx context.Context, arg UpdateOrganizationLogoParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationLogo, arg.ID, arg.LogoUrl)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.OwnerID,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
