// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertSlotsParams struct {
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	EndAt           pgtype.Timestamptz `json:"end_at"`
}

const countSlotsByOrgOnLocalDay = `-- name: CountSlotsByOrgOnLocalDay :one
SELECT COUNT(*)::int AS slot_count
FROM slots
WHERE organization_id = $1
  AND start_at >= $2
  AND start_at < $3
`

type CountSlotsByOrgOnLocalDayParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	StartAt_2      pgtype.Timestamptz `json:"start_at_2"`
}

// $2 = local day start (UTC), $3 = local day end (UTC) — compute in Go from org timezone
func (q *Queries) CountSlotsByOrgOnLocalDay(ctx context.Context, arg CountSlotsByOrgOnLocalDayParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSlotsByOrgOnLocalDay, arg.OrganizationID, arg.StartAt, arg.StartAt_2)
	var slot_count int32
	err := row.Scan(&slot_count)
	return slot_count, err
}

const deleteUnbookedSlotsByOrgInWindow = `-- name: DeleteUnbookedSlotsByOrgInWindow :exec
DELETE FROM slots AS s
WHERE s.organization_id = $1
  AND s.booked = FALSE
  AND s.start_at >= $2
  AND s.start_at < $3
  AND NOT EXISTS (
    SELECT 1 FROM booking b WHERE b.slot_id = s.id
  )
`

type DeleteUnbookedSlotsByOrgInWindowParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	StartAt_2      pgtype.Timestamptz `json:"start_at_2"`
}

func (q *Queries) DeleteUnbookedSlotsByOrgInWindow(ctx context.Context, arg DeleteUnbookedSlotsByOrgInWindowParams) error {
	_, err := q.db.Exec(ctx, deleteUnbookedSlotsByOrgInWindow, arg.OrganizationID, arg.StartAt, arg.StartAt_2)
	return err
}

const deleteUnbookedSlotsByTypeAfter = `-- name: DeleteUnbookedSlotsByTypeAfter :exec
DELETE FROM slots AS s
WHERE s.interview_type_id = $1
  AND s.booked = FALSE
  AND s.start_at >= $2
  AND NOT EXISTS (
    SELECT 1 FROM booking b WHERE b.slot_id = s.id
  )
`

type DeleteUnbookedSlotsByTypeAfterParams struct {
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) DeleteUnbookedSlotsByTypeAfter(ctx context.Context, arg DeleteUnbookedSlotsByTypeAfterParams) error {
	_, err := q.db.Exec(ctx, deleteUnbookedSlotsByTypeAfter, arg.InterviewTypeID, arg.StartAt)
	return err
}

const deleteUnbookedSlotsByTypeInWindow = `-- name: DeleteUnbookedSlotsByTypeInWindow :exec
DELETE FROM slots AS s
WHERE s.interview_type_id = $1
  AND s.booked = FALSE
  AND s.start_at >= $2
  AND s.start_at < $3
  AND NOT EXISTS (
    SELECT 1 FROM booking b WHERE b.slot_id = s.id
  )
`

type DeleteUnbookedSlotsByTypeInWindowParams struct {
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	StartAt_2       pgtype.Timestamptz `json:"start_at_2"`
}

func (q *Queries) DeleteUnbookedSlotsByTypeInWindow(ctx context.Context, arg DeleteUnbookedSlotsByTypeInWindowParams) error {
	_, err := q.db.Exec(ctx, deleteUnbookedSlotsByTypeInWindow, arg.InterviewTypeID, arg.StartAt, arg.StartAt_2)
	return err
}

const getSlotByID = `-- name: GetSlotByID :one
SELECT id, organization_id, interview_type_id, start_at, end_at, booked, created_at
FROM slots
WHERE id = $1
`

func (q *Queries) GetSlotByID(ctx context.Context, id pgtype.UUID) (Slot, error) {
	row := q.db.QueryRow(ctx, getSlotByID, id)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.StartAt,
		&i.EndAt,
		&i.Booked,
		&i.CreatedAt,
	)
	return i, err
}

const insertSlot = `-- name: InsertSlot :one
INSERT INTO slots (
    organization_id,
    interview_type_id,
    start_at,
    end_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, interview_type_id, start_at, end_at, booked, created_at
`

type InsertSlotParams struct {
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	EndAt           pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) InsertSlot(ctx context.Context, arg InsertSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, insertSlot,
		arg.OrganizationID,
		arg.InterviewTypeID,
		arg.StartAt,
		arg.EndAt,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InterviewTypeID,
		&i.StartAt,
		&i.EndAt,
		&i.Booked,
		&i.CreatedAt,
	)
	return i, err
}

const listAvailableSlotsByType = `-- name: ListAvailableSlotsByType :many
SELECT id, organization_id, interview_type_id, start_at, end_at, booked, created_at
FROM slots
WHERE organization_id = $1
  AND interview_type_id = $2
  AND booked = FALSE
  AND start_at >= $3
  AND start_at < $4
ORDER BY start_at
`

type ListAvailableSlotsByTypeParams struct {
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	StartAt_2       pgtype.Timestamptz `json:"start_at_2"`
}

func (q *Queries) ListAvailableSlotsByType(ctx context.Context, arg ListAvailableSlotsByTypeParams) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listAvailableSlotsByType,
		arg.OrganizationID,
		arg.InterviewTypeID,
		arg.StartAt,
		arg.StartAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InterviewTypeID,
			&i.StartAt,
			&i.EndAt,
			&i.Booked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsByTypeInWindow = `-- name: ListSlotsByTypeInWindow :many
SELECT id, organization_id, interview_type_id, start_at, end_at, booked, created_at
FROM slots
WHERE interview_type_id = $1
  AND start_at >= $2
  AND start_at < $3
ORDER BY start_at
`

type ListSlotsByTypeInWindowParams struct {
	InterviewTypeID pgtype.UUID        `json:"interview_type_id"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	StartAt_2       pgtype.Timestamptz `json:"start_at_2"`
}

func (q *Queries) ListSlotsByTypeInWindow(ctx context.Context, arg ListSlotsByTypeInWindowParams) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listSlotsByTypeInWindow, arg.InterviewTypeID, arg.StartAt, arg.StartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InterviewTypeID,
			&i.StartAt,
			&i.EndAt,
			&i.Booked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSlotBooked = `-- name: SetSlotBooked :exec
UPDATE slots
SET booked = $2
WHERE id = $1
`

type SetSlotBookedParams struct {
	ID     pgtype.UUID `json:"id"`
	Booked bool        `json:"booked"`
}

func (q *Queries) SetSlotBooked(ctx context.Context, arg SetSlotBookedParams) error {
	_, err := q.db.Exec(ctx, setSlotBooked, arg.ID, arg.Booked)
	return err
}
