// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserGoogleConnection = `-- name: ClearUserGoogleConnection :exec
UPDATE users
SET
    google_id = NULL,
    google_refresh_token = NULL,
    google_connected_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearUserGoogleConnection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearUserGoogleConnection, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, last_login_at, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGoogleCredentials = `-- name: GetUserGoogleCredentials :one
SELECT google_id, google_refresh_token, google_connected_at
FROM users
WHERE id = $1
`

type GetUserGoogleCredentialsRow struct {
	GoogleID           pgtype.Text        `json:"google_id"`
	GoogleRefreshToken pgtype.Text        `json:"google_refresh_token"`
	GoogleConnectedAt  pgtype.Timestamptz `json:"google_connected_at"`
}

func (q *Queries) GetUserGoogleCredentials(ctx context.Context, id pgtype.UUID) (GetUserGoogleCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getUserGoogleCredentials, id)
	var i GetUserGoogleCredentialsRow
	err := row.Scan(&i.GoogleID, &i.GoogleRefreshToken, &i.GoogleConnectedAt)
	return i, err
}

const isGoogleConnected = `-- name: IsGoogleConnected :one
SELECT (google_connected_at IS NOT NULL)::bool AS connected
FROM users
WHERE id = $1
`

func (q *Queries) IsGoogleConnected(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isGoogleConnected, id)
	var connected bool
	err := row.Scan(&connected)
	return connected, err
}

const setUserGoogleConnection = `-- name: SetUserGoogleConnection :exec
UPDATE users
SET
    google_id = $2,
    google_refresh_token = $3,
    google_connected_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type SetUserGoogleConnectionParams struct {
	ID                 pgtype.UUID `json:"id"`
	GoogleID           pgtype.Text `json:"google_id"`
	GoogleRefreshToken pgtype.Text `json:"google_refresh_token"`
}

func (q *Queries) SetUserGoogleConnection(ctx context.Context, arg SetUserGoogleConnectionParams) error {
	_, err := q.db.Exec(ctx, setUserGoogleConnection, arg.ID, arg.GoogleID, arg.GoogleRefreshToken)
	return err
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}
